/**
 * ECON structured learning path — units, lessons, practice gates.
 * Lesson content generated by Lesson bot (DeepSeek -> GLM review),
 * stored in src/data/dse/econ-lessons.json.
 */
import econDrills from "@/data/dse/econ-drills.json";
import type { DrillQuestion } from "./drills";

export type LessonContent = {
  /** Lesson 1.1 etc. */
  id: string;
  title: string;
  /** 150-250 word concept explanation */
  concept: string;
  example: {
    scenario: string;
    walkthrough: string;
  };
  /** 2-4 common exam traps */
  traps: string[];
  /** key terms defined in this lesson */
  terms: { term: string; definition: string }[];
};

export type Lesson = LessonContent & {
  unitId: number;
  /** drill topic key to pull practice questions from */
  practiceTopic: string;
  /** min correct out of practice set to unlock next lesson/unit */
  passThreshold: number;
};

export type Unit = {
  id: number;
  title: string;
  topicKey: string;
  /** ids of units that must be completed first */
  prerequisites: number[];
  lessonIds: string[];
  /** min correct out of 10-question practice to complete the unit */
  passThreshold: number;
};

export const ECON_UNITS: Unit[] = [
  { id: 1, title: "Demand & Supply", topicKey: "demand-and-supply", prerequisites: [], lessonIds: ["L1.1", "L1.2", "L1.3"], passThreshold: 7 },
  { id: 2, title: "Elasticity", topicKey: "elasticity", prerequisites: [1], lessonIds: ["L2.1", "L2.2"], passThreshold: 7 },
  { id: 3, title: "Market Intervention", topicKey: "market-intervention", prerequisites: [1], lessonIds: ["L3.1", "L3.2"], passThreshold: 7 },
  { id: 4, title: "Production & Costs", topicKey: "production-costs", prerequisites: [1], lessonIds: ["L4.1", "L4.2"], passThreshold: 7 },
  { id: 5, title: "Market Structures", topicKey: "market-structures", prerequisites: [1, 4], lessonIds: ["L5.1", "L5.2"], passThreshold: 7 },
  { id: 6, title: "GDP & National Income", topicKey: "gdp", prerequisites: [], lessonIds: ["L6.1", "L6.2"], passThreshold: 7 },
  { id: 7, title: "Inflation & Unemployment", topicKey: "inflation-unemployment", prerequisites: [6], lessonIds: ["L7.1", "L7.2"], passThreshold: 7 },
  { id: 8, title: "Money & Banking", topicKey: "money-banking", prerequisites: [6], lessonIds: ["L8.1", "L8.2"], passThreshold: 7 },
  { id: 9, title: "Fiscal & Monetary Policy", topicKey: "fiscal-monetary-policy", prerequisites: [7, 8], lessonIds: ["L9.1", "L9.2"], passThreshold: 7 },
  { id: 10, title: "International Trade", topicKey: "international-trade", prerequisites: [1], lessonIds: ["L10.1", "L10.2"], passThreshold: 7 },
];

/** Practice set = questions from the unit's topic, mixed difficulty. */
export function getPracticeSet(topicKey: string, n = 10): DrillQuestion[] {
  const qs = (econDrills as { questions: DrillQuestion[] }).questions.filter(
    (q) => q.topic === topicKey,
  );
  // interleave difficulties so the set isn't front-loaded
  const byDiff: Record<string, DrillQuestion[]> = { easy: [], medium: [], hard: [] };
  for (const q of qs) (byDiff[q.difficulty] ||= []).push(q);
  const out: DrillQuestion[] = [];
  while (out.length < n && (byDiff.easy.length || byDiff.medium.length || byDiff.hard.length)) {
    if (byDiff.easy.length) out.push(byDiff.easy.shift()!);
    if (byDiff.medium.length && out.length < n) out.push(byDiff.medium.shift()!);
    if (byDiff.hard.length && out.length < n) out.push(byDiff.hard.shift()!);
  }
  return out;
}

export function unitUnlocked(unit: Unit, completed: number[]): boolean {
  return unit.prerequisites.every((p) => completed.includes(p));
}
